### ISSUE TITLE
.on_event('startup') is deprecated

### ISSUE THREAD

**Issue by vorenhoutgithub** [priyanshu-panwar/fastapi-utilities#13]
See https://fastapi.tiangolo.com/advanced/events/#alternative-events-deprecated

Can you please provide the current way to add repeat_every() functions?

**Comment by priyanshu-panwar** [comment]
Hi @vorenhoutgithub Thanks for bringing this to my notice.
I'll check this now.

**Comment by priyanshu-panwar** [comment]
The functions `repeat_at` and `repeat_every` work for the time being after the depreciation of the alternative events like `app.on_startup()`.
I'll try to figure out a solution for this issue asap. Need to add our functions in the lifespan of the app.

**Comment by cm-halfspace** [comment]
Any update on this?

**Comment by mareksDev** [comment]
This library seems exactly the right solution to my problem, but yes, exactly the same concern that it is not possible to use it with the newest version. Are there any updates or an expected time when there might be an update?

**Comment by priyanshu-panwar** [comment]
I found a workaround for this.
```
from fastapi import FastAPI
from contextlib import asynccontextmanager
from fastapi_utilities.repeat import repeat_every, repeat_at

utils = {}


@asynccontextmanager
async def lifespan(app: FastAPI):
    # --- startup ---
    # Load utils
    utils["repeat_every_fun"] = repeat_every
    utils["repeat_at_fun"] = repeat_at
    # call funcs
    await events()
    # --- ---
    yield
    # --- shutdown ---
    utils.clear()
    # --- ---


app = FastAPI(lifespan=lifespan)

async def events():
    # Define your events here

    # Repeat Every Example
    re = utils["repeat_every_fun"]
    @re(seconds=2)
    async def test():
        print("test")
    await test()

    # Repeat At Example
    ra = utils["repeat_at_fun"]
    @ra(cron="* * * * *")
    def test2():
        print("test2")
    test2()
```

This works fine.
We need to use`asynccontextmanager`.
I'll try to see if we can fix anything in our framework.
Till then please use this and let me know the reviews.

**Comment by priyanshu-panwar** [comment]
I feel this solution is enough for us.
@mareksDev @cm-halfspace @vorenhoutgithub Please let me know and merge the above PR.

**Comment by vorenhoutgithub** [comment]
The documentation is here https://fastapi.tiangolo.com/advanced/events/#async-context-manager
Can you also add that to the docs here?
